# Generated by Django 4.1.4 on 2023-01-03 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0003_employee_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employee',
        ),
        migrations.DeleteModel(
            name='teacher',
        ),
    ]
